version: '3.3'

services:
  app:
    image: node:8.6-alpine
    working_dir: "${PWD}"
    command: npm start
    environment:
      - DEV_SERVER_PORT=4200
    ports:
      - "4200:4200" # http
    volumes:
      - ".:${PWD}"
