version: '3.3'

volumes:
  npm:

services:
  app:
    image: node:8.11-alpine
    working_dir: /app
    command: npm start
    environment:
      - DEV_SERVER_PORT=4200
    ports:
      - "4200:4200" # http
    volumes:
      - .:/app
      - npm:/app/node_modules
